---
title: "List of participants"
---

- Maria Alberich-Carramiñana, Universitat Politècnica de Catalunya
- Patricio Almirón, Universidad de Valladolid
- Abdallah Assi, LAREMA, Universitè d'Angers
- Alberto Calabri, Università degli Studi di Ferrara
- Pietro Campochiaro, Jagiellonian University
- Marco D'Anna, Università degli Studi di Catania
- Hailong Dao, University of Kansas
- Biplab Dawn,	Indian institute of technology Patna
- Félix Delgado, Universidad de Valladolid
- Carmelo Antonio Finocchiaro, Università degli Studi di Catania
- Ines Gam, University of Monastir
- Pedro A. García Sánchez, Universidad de Granada
- William Giovanni Hernández Yanes, Universidad de La Laguna
- Lorenzo Guerrieri, Jagiellonian University in Krakow
- Ahmed Hamed, University of Monastir
- Rajesh Kumar Sau, University of Messina
- Nicola Maugeri, Università degli Studi di Catania
- Vincenzo Micale, Università degli Studi di Catania
- Alessio Moscariello, University of Graz
- Julio Moyano, Universitat Jaume I
- Francesco Russo, Università degli Studi di Catania
- Alessio Sammartano, Politecnico di Milano
- Vincenzo Scarvaglieri, Università degli Studi di Catania
- Indranath Sengupta, IIT Gandhinagar
- Dumitru Stamate, University of Bucharest
- Francesco Strazzanti, University of Messina
- Yotam Svoray, University of Utah
- Keiichi Watanabe, Nihon University
